#!/bin/sh

case "$1" in
        start)
                echo KB wirelss check start : ok
                ifconfig wlan0 up
                wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
                udhcpc -i wlan0 &
                ;;
        stop)
                echo KB wirelss check stop : ok
                ifconfig wlan0 down
                ;;
        *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?
